#!/bin/ksh
total=0
c=0
for a in {1,2,3,4,5,6,7};  # iterate loop 7 times...the number inside is the $a
	do
		echo "$a time: Enter a number . . .: "
		read i
		if [ $i -ge 250 ] ; then let "c=c+1" ; fi
		let "total = i + total"	
	done
echo "total = $total"
echo " > 250 = $c "