#!/bin/sh
# add colon @ pos # 81 - doesn't work
# invocation: sed_inserting_char_@_pos_81.sh
cat 	input_file_for_adding_char_@_pos_81
set -x  # turn on debugging
sed 's/./&:/80' <input_file_for_adding_char_@_pos_81 >output_file_for_adding_char_@_pos_81
set +x  # turn off debugging
cat 	output_file_for_adding_char_@_pos_81