#!/usr/bin/bash
# Adding and renaming and listing and deleting soft links
# Setup before running this SS: mkdir 1.3 / mkdir 1.2
ln -s 1.3 latest
ls -ltra | grep "^l" 
echo " "
ln -nsf 1.2 latest
ls -ltra | grep "^l"
echo " "
ln -nsf 1.3 latest
ls -ltra | grep "^l"
echo " "
ln -s 1.2 previous
ls -ltra | grep "^l"
echo " "
# find all of the symbolic links; prints the filename that your symbolic links point to (the filename is contained within column # 11 of the ls output)
# type l means "type link" / the "d" option of the ls means " lists directories only" 
find . -type l -print | xargs ls -ld | awk '{print $11}'
echo " "
rm latest previous
ls -ltra | grep "^l"

